# Generated by Django 4.2 on 2024-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('L', 'Lagartija'), ('P', 'Planta'), ('A', 'Agua')], max_length=30),
        ),
    ]
