# Generated by Django 4.2 on 2024-08-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('T', 'Tierra'), ('F', 'Fuego'), ('P', 'Planta'), ('A', 'Agua'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
